[package]
name = "skunk-bat-core"
description = "Reconnaissance & Automated Defense"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
tokio = { version = "1.40", features = ["sync"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tarpc = { workspace = true }

[dev-dependencies]
tokio = { version = "1.40", features = ["rt-multi-thread", "macros", "test-util"] }
tracing-subscriber = { workspace = true }
tempfile = "3"

