#!/bin/bash
set -e

echo "🦨 + 🐻 Ownership Breach Response Demo"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Responding to device theft with genetic revocation..."
echo ""
sleep 1

echo "═══════════════════════════════════════════"
echo "SCENARIO: Stolen Tower"
echo "═══════════════════════════════════════════"
echo ""
echo "Your tower-laptop (genetic ID: tower-xyz-123) is stolen."
echo "Thief attempts to access your data federation."
echo ""
sleep 2

echo "Step 1: You detect the breach"
echo "  • Physical device missing"
echo "  • Unusual access patterns from tower-xyz-123"
echo "  • Location mismatch (device in wrong city)"
echo ""
sleep 1

echo "Step 2: You revoke genetic lineage (Beardog)"
echo "  → Executing: beardog revoke tower-xyz-123"
echo "  → Lineage cryptographically invalidated"
echo "  ✓ Revocation published to mesh"
echo ""
sleep 1

echo "Step 3: Mesh receives revocation"
echo "  → skunkBat-home: tower-xyz-123 revoked"
echo "  → skunkBat-family: tower-xyz-123 revoked"
echo "  → skunkBat-uni: tower-xyz-123 revoked"
echo "  → skunkBat-friends: tower-xyz-123 revoked"
echo ""
sleep 1

echo "Step 4: Thief attempts access"
echo ""
echo "  Thief → NestGate public API:"
echo "    Request: \"Access my data\""
echo "    Identity: tower-xyz-123"
echo ""
echo "  → skunkBat-api genetic check:"
echo "    Beardog: REVOKED LINEAGE"
echo "    ✗ Connection DENIED"
echo ""
echo "  Thief → Direct family tower:"
echo "    Request: \"Sync data\""
echo "    Identity: tower-xyz-123"
echo ""
echo "  → skunkBat-family genetic check:"
echo "    Beardog: REVOKED LINEAGE"
echo "    ✗ Connection DENIED"
echo ""
echo "  Thief → Storage layer bypass attempt:"
echo "    Request: Direct storage access"
echo "    Identity: tower-xyz-123"
echo ""
echo "  → skunkBat-storage checks:"
echo "    1. Genetic: REVOKED LINEAGE"
echo "    2. Topology: Invalid path"
echo "    ✗ Connection DENIED (double violation)"
echo ""
sleep 2

echo "Step 5: Mesh-wide results"
echo ""
echo "  ✓ ALL access denied across entire federation"
echo "  ✓ Attempts logged for forensics"
echo "  ✓ Alerts sent to federation owners"
echo "  ✓ Zero data exfiltration"
echo ""

echo "═══════════════════════════════════════════"
echo "WHY THIS WORKS"
echo "═══════════════════════════════════════════"
echo ""
echo "1. Genetic Identity (Beardog)"
echo "   • Cryptographic lineage, not passwords"
echo "   • Can't be guessed or brute-forced"
echo "   • Revocation is instant and irreversible"
echo ""
echo "2. Mesh Coordination (Songbird)"
echo "   • Revocation propagates to all skunkBats"
echo "   • No central point of failure"
echo "   • Each node validates independently"
echo ""
echo "3. Defense in Depth (skunkBat)"
echo "   • Genetic check at every layer"
echo "   • Topology validation prevents bypasses"
echo "   • Multiple violation types = multiple defenses"
echo ""

echo "✅ Demo Complete!"
echo ""
echo "Key Takeaway: Ownership breach → Genetic revocation → Mesh-wide denial!"
echo "YOUR data stays YOURS, even if hardware is stolen!"
echo ""
echo "➡️  Next: ../04-data-exfiltration/"

