#!/bin/bash
set -e

echo "🦨 + 🐻 + 🍄 + 🐦 Complete Ecosystem Demo"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "All three integrations working together..."
echo ""
sleep 1

echo "════════════════════════════════════════════════════════"
echo "SCENARIO: Sophisticated Attack on Federated Network"
echo "════════════════════════════════════════════════════════"
echo ""
echo "Attacker strategy:"
echo "  1. Spoof trusted node identity"
echo "  2. Find Beardog via network scan"
echo "  3. Launch distributed DoS"
echo ""
sleep 2

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "DEFENSE: Coordinated Response"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "Step 1: Toadstool (Discovery)"
echo "  Attacker query: \"Where is beardog-tower?\""
echo "  → Toadstool: Access denied (not authorized)"
echo "  ✓ Discovery prevented"
echo ""
sleep 1

echo "Step 2: Beardog (Identity)"
echo "  Attacker connection: \"I'm trusted-node-123\""
echo "  → Beardog: Lineage check failed"
echo "  → skunkBat: Genetic violation detected"
echo "  ✓ Spoofing caught"
echo ""
sleep 1

echo "Step 3: skunkBat (Detection)"
echo "  Observation: 500 req/s from attacker-node"
echo "  → Baseline profiler: 19.5σ anomaly"
echo "  → Resource monitor: CPU 95%, bandwidth 3x limit"
echo "  ✓ DoS detected"
echo ""
sleep 1

echo "Step 4: Songbird (Coordination)"
echo "  → Broadcasting threat to federation..."
echo "  → 3 peer skunkBats notified"
echo "  ✓ Federation coordinated"
echo ""
sleep 1

echo "Step 5: Federated Response"
echo ""
echo "  skunkBat-home (YOUR decision):"
echo "    Action: BLOCK attacker-node"
echo "    Reasoning: Critical severity, owner policy"
echo ""
echo "  skunkBat-family (THEIR decision):"
echo "    Action: BLOCK attacker-node"
echo "    Reasoning: Trust YOUR intel, shared threat"
echo ""
echo "  skunkBat-uni (THEIR decision):"
echo "    Action: RATE LIMIT attacker-node"
echo "    Reasoning: Cautious policy, validate first"
echo ""
sleep 2

echo "════════════════════════════════════════════════════════"
echo "ATTACK TIMELINE: Stopped at Multiple Layers"
echo "════════════════════════════════════════════════════════"
echo ""
echo "  [0s] Attacker scans for Beardog"
echo "    ↓"
echo "  [1s] ✗ Toadstool: Discovery denied"
echo "    ↓"
echo "  [2s] Attacker tries direct connection"
echo "    ↓"
echo "  [3s] ✗ Beardog: Identity verification failed"
echo "    ↓"
echo "  [4s] Attacker launches DoS"
echo "    ↓"
echo "  [5s] ✗ skunkBat: Resource exhaustion detected"
echo "    ↓"
echo "  [6s] Songbird: Federation notified"
echo "    ↓"
echo "  [7s] ✓ Network-wide block coordinated"
echo ""

echo "════════════════════════════════════════════════════════"
echo "ECOSYSTEM SYNERGY"
echo "════════════════════════════════════════════════════════"
echo ""
echo "Toadstool: \"I handle WHO can discover WHAT\""
echo "  ✓ Prevented attacker from finding targets"
echo ""
echo "Beardog: \"I verify WHO you genetically are\""
echo "  ✓ Caught identity spoofing"
echo ""
echo "skunkBat: \"I detect WHAT violations occur\""
echo "  ✓ Detected DoS attack pattern"
echo ""
echo "Songbird: \"I coordinate HOW we respond together\""
echo "  ✓ Enabled federated defense"
echo ""

echo "✅ Demo Complete!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎉 LEVEL 1 COMPLETE!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "You've mastered ecosystem integration!"
echo ""
echo "Next Level: ../../02-federation-mesh/"
echo "Learn multi-network federation scenarios!"

