#!/bin/bash
set -e

echo "🦨 Disaster Recovery Demo"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Testing failure scenarios..."
echo ""
sleep 1

echo "═══════════════════════════════════════════"
echo "SCENARIO 1: Beardog Unavailable"
echo "═══════════════════════════════════════════"
echo ""
echo "Beardog service crashes..."
echo "  ✗ Lineage verification unavailable"
echo ""
echo "skunkBat response:"
echo "  → Fallback: Deny genetic verification"
echo "  → Log: Warning about Beardog unavailability"
echo "  → Continue: Other detection types still work"
echo ""
echo "  ✓ Topology detection: Still operational"
echo "  ✓ Behavioral detection: Still operational"
echo "  ✓ Resource detection: Still operational"
echo ""
sleep 2

echo "═══════════════════════════════════════════"
echo "SCENARIO 2: Network Partition"
echo "═══════════════════════════════════════════"
echo ""
echo "Songbird mesh partitioned..."
echo "  ✗ Federation coordination unavailable"
echo ""
echo "skunkBat response:"
echo "  → Local defense: Continues independently"
echo "  → Queue threats: Store for later sync"
echo "  → Log: Warning about partition"
echo ""
echo "When partition heals:"
echo "  → Sync queued threats"
echo "  → Resume coordination"
echo "  ✓ Zero data loss"
echo ""
sleep 2

echo "═══════════════════════════════════════════"
echo "SCENARIO 3: Memory Pressure"
echo "═══════════════════════════════════════════"
echo ""
echo "System running low on memory..."
echo "  ⚠ Available memory: 10%"
echo ""
echo "skunkBat response:"
echo "  → Reduce baseline window size (1000 → 100)"
echo "  → Disable non-critical logging"
echo "  → Continue critical operations"
echo ""
echo "  ✓ Threat detection: Still operational"
echo "  ✓ Defense actions: Still operational"
echo ""
sleep 2

echo "═══════════════════════════════════════════"
echo "SCENARIO 4: Crash Recovery"
echo "═══════════════════════════════════════════"
echo ""
echo "skunkBat crashes unexpectedly..."
echo "  ✗ Process terminated"
echo ""
echo "On restart:"
echo "  → Load persisted baseline (if enabled)"
echo "  → Resume threat detection"
echo "  → Sync missed threats from federation"
echo "  ✓ Graceful recovery"
echo ""

echo "✅ Demo Complete!"
echo ""
echo "Key Takeaway: Resilient by design - graceful degradation!"
echo ""
echo "➡️  Next: ../05-production-checklist/"

