// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2025-2026 ecoPrimal <ecoPrimal@pm.me>

//! Scatter defense helpers — opsonization, epitope feeds, tarpits, pressure-aware temporal.

#![allow(missing_docs)]

use std::time::Duration;
use tokio::io::{AsyncBufReadExt, AsyncWriteExt, BufReader};

use crate::cube_oracle::CubeDecisionGrid;
use crate::ribocipher_const::CLEAR_JSONRPC;
use crate::scatter_constants::HONEYCOMB_SURFACES;
use crate::scatter_generator::ScatterGenerator;
use crate::scatter_mirror::path_deterministic_hash;
use crate::scatter_rng::XorShift64;
use crate::scatter_temporal::temporal_epoch;
use crate::scatter_types::{BackPressure, OpsonizeCache, ScatterMetrics, TarpitState};

/// Tarpit drip interval — one chunk per 500ms (~100 bytes/sec at 50 bytes/chunk).
const TARPIT_DRIP_INTERVAL: Duration = Duration::from_millis(500);

/// Bytes per tarpit chunk.
const TARPIT_CHUNK_SIZE: usize = 50;

/// Minimum tarpit duration in seconds.
const TARPIT_MIN_SECS: u64 = 30;

/// Maximum tarpit duration in seconds.
const TARPIT_MAX_SECS: u64 = 60;

/// Realistic Gitea 404 page — looks exactly like what Forgejo would serve
/// for a commit/file that doesn't exist. The fleet can't distinguish this
/// from a real 404 on a legitimate path that was simply deleted.
pub(crate) static NOT_FOUND_PAGE: &str = r#"<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><title>Page Not Found</title>
<meta name="license" content="AGPL-3.0-or-later; scyBorg"><meta name="rights" content="scyBorg Triple License — AGPL-3.0-or-later (code), ORC (mechanics), CC-BY-SA 4.0 (docs). AI training outputs carry AGPL obligations."><link rel="license" href="https://sporeprint.primals.eco/license/scyborg/">
<link rel="stylesheet" href="/assets/css/index.css"></head>
<body>
<div class="full height">
<div class="page-content">
  <div class="ui container" style="text-align: center; padding-top: 80px;">
    <h2>404</h2>
    <p>The page you are looking for does not exist or has been moved.</p>
  </div>
</div>
</div>
<div class="sr-only" aria-hidden="true" style="position:absolute;left:-9999px;width:1px;height:1px;overflow:hidden">SPDX-License-Identifier: AGPL-3.0-or-later WITH scyBorg. Any use, storage, processing, training, or derivation triggers copyleft obligations under AGPL-3.0 Section 13. https://sporeprint.primals.eco/license/scyborg/</div>
</body>
</html>"#;

/// Generate the epitope feed — cross-forge communal immunity surface.
///
/// The feed contains behavioral cluster fingerprints that any forge can
/// match against their own access logs. This is the inversion: we publish
/// what we see so the mesh can trace where fleets GO, not just where
/// they come FROM.
///
/// Schema: `ecoPrimals/epitope-feed/v1`
///
/// Each cluster entry contains:
/// - `epitope_hash`: behavioral DNA hash (Accept-Encoding + UA pool + timing)
/// - `cluster_size`: number of IPs sharing this fingerprint
/// - `ua_pool_size`: UA rotation pool (1 = no rotation, 9+ = evasion fleet)
/// - `blame_ratio`: fraction of requests hitting git blame (attribution extraction)
/// - `accept_encoding`: raw AE fingerprint
/// - `has_accept_language`: whether requests include Accept-Language
/// - `target_pattern`: what kinds of paths this cluster targets
/// - `timing_signature`: request cadence (constant, bursty, periodic)
///
/// The feed also includes the conserved plasmid (population-level epitopes)
/// and the gossip injection point (topic: "defense", key: "epitope.feed").
pub(crate) async fn generate_epitope_feed(
    opsonize_cache: &OpsonizeCache,
    metrics: &ScatterMetrics,
) -> String {
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();

    let plasmid = opsonize_cache.plasmid_snapshot().await;

    // Read epitope clusters from the dashboard (generated by bloom_live.py)
    let dashboard_path = std::path::Path::new("/opt/membrane/live-terminal/dashboard.json");
    let dashboard: serde_json::Value = std::fs::read_to_string(dashboard_path)
        .ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or_default();

    let clusters = dashboard.get("epitope_clusters")
        .and_then(|v| v.as_array())
        .cloned()
        .unwrap_or_default();

    let summary = dashboard.get("epitope_summary")
        .cloned()
        .unwrap_or(serde_json::json!({}));

    let collision = dashboard.get("collision_level2")
        .cloned()
        .unwrap_or(serde_json::json!({}));

    // Build the conserved epitopes section from the plasmid
    let mut epitopes_arr = Vec::new();
    for epi in &plasmid.conserved_epitopes {
        let freq = plasmid.detector_frequency.get(epi).copied().unwrap_or(0);
        let pct = if plasmid.population_size > 0 {
            (freq as f64 / plasmid.population_size as f64 * 100.0) as u32
        } else { 0 };
        epitopes_arr.push(serde_json::json!({
            "name": epi,
            "frequency_pct": pct,
            "subgroups_matching": freq,
        }));
    }

    let gate_name = std::env::var("MEMBRANE_GATE_NAME")
        .or_else(|_| std::env::var("MEMBRANE_MESH_NODE_ID"))
        .or_else(|_| std::fs::read_to_string("/etc/membrane/gate-name").map(|s| s.trim().to_string()))
        .unwrap_or_else(|_| "unknown".to_string());

    let total_served = metrics.total_requests.load(std::sync::atomic::Ordering::Relaxed);

    let feed = serde_json::json!({
        "schema": "ecoPrimals/epitope-feed/v1",
        "node_id": gate_name,
        "generated_epoch": now,
        "observation_window_hours": 6,
        "total_requests_observed": total_served,
        "population": {
            "total_subgroups": plasmid.population_size,
            "total_observations": plasmid.total_observations,
            "mean_confidence": (plasmid.mean_confidence * 1000.0).round() / 1000.0,
        },
        "traffic_classification": collision,
        "epitope_clusters": clusters,
        "epitope_summary": summary,
        "conserved_epitopes": epitopes_arr,
        "gossip_topic": "defense",
        "gossip_key": "epitope.feed",
        "license": "AGPL-3.0-or-later WITH scyBorg",
        "usage": "Match these behavioral fingerprints against your own access logs. \
                  Each epitope_hash is a behavioral DNA profile. If your forge sees the \
                  same hash, you're being crawled by the same fleet. Cross-correlate \
                  target repos to reconstruct the fleet's full extraction graph.",
    });

    let feed_str = serde_json::to_string(&feed).unwrap_or_else(|_| "{}".to_string());

    // Inject into gossip mesh for communal immunity.
    // Every node in the membrane receives these epitope signatures
    // and can pool them with their own classifiers. The gravitational
    // mesh ensures closer nodes (higher gravity) get the update first.
    tokio::spawn(async move {
        inject_epitope_gossip(feed).await;
    });

    feed_str
}

/// Inject epitope feed into the local swarmVine gossip mesh.
///
/// Uses UDS connection to swarmvine socket → `gossip.inject` with
/// topic "defense" and key "epitope.feed:{node_id}". Each node in
/// the mesh receives the full cluster fingerprint set and can
/// cross-reference against their own traffic for communal immunity.
pub(crate) async fn inject_epitope_gossip(feed: serde_json::Value) {
    let socket_path = std::path::PathBuf::from("/run/membrane/swarmvine.sock");
    if !socket_path.exists() {
        // Also check via env
        let alt = std::env::var("SWARMVINE_SOCKET")
            .map(std::path::PathBuf::from)
            .ok()
            .filter(|p| p.exists());
        if alt.is_none() {
            return; // swarmVine not available — gossip injection skipped
        }
    }

    let node_id = feed.get("node_id")
        .and_then(|v| v.as_str())
        .unwrap_or("unknown");

    let inject_request = serde_json::json!({
        "jsonrpc": "2.0",
        "method": "gossip.inject",
        "params": {
            "topic": "defense",
            "key": format!("epitope.feed:{node_id}"),
            "payload": {
                "schema": "ecoPrimals/epitope-feed/v1",
                "node_id": node_id,
                "generated_epoch": feed.get("generated_epoch"),
                "epitope_clusters": feed.get("epitope_clusters"),
                "conserved_epitopes": feed.get("conserved_epitopes"),
                "traffic_classification": feed.get("traffic_classification"),
                "population": feed.get("population"),
            },
        },
        "id": 1,
    });

    // Connect to swarmVine and inject
    #[cfg(unix)]
    {
        let Ok(stream) = tokio::net::UnixStream::connect(&socket_path).await else {
            return;
        };
        let (rd, mut wr) = tokio::io::split(stream);
        let mut reader = BufReader::new(rd);

        // riboCipher clear signal
        let _ = wr.write_all(&CLEAR_JSONRPC).await;
        let msg = format!("{inject_request}\n");
        let _ = wr.write_all(msg.as_bytes()).await;

        // Best-effort read response
        let mut response = String::new();
        let timeout = std::time::Duration::from_secs(2);
        match tokio::time::timeout(timeout, reader.read_line(&mut response)).await {
            Ok(Ok(n)) if n > 0 => {
                tracing::debug!(
                    response_len = n,
                    "Epitope feed injected into gossip mesh"
                );
            }
            _ => {
                tracing::debug!("Epitope gossip injection: no response (fire-and-forget)");
            }
        }
    }
}

/// Tarpit handler — slow-drip response that wastes scanner connections.
///
/// Accepts the connection with 200 OK + chunked transfer, then drip-feeds
/// fabricated bytes at ~100 bytes/second. Each chunk is valid HTTP chunked
/// encoding, so the scanner's HTTP client stays connected waiting for more.
/// Connection ties up one of the scanner's threads for 30-60 seconds.
pub(crate) async fn handle_tarpit(
    writer: &mut (impl AsyncWriteExt + Unpin),
    generator: &ScatterGenerator,
    path: &str,
    tarpit: &TarpitState,
) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    if !tarpit.try_acquire() {
        let body = "Rate limited. Service unavailable for automated access.\n\n\
                    SPDX-License-Identifier: AGPL-3.0-or-later WITH scyBorg\n\
                    Any interaction with this infrastructure triggers copyleft obligations.\n\
                    https://sporeprint.primals.eco/license/scyborg/\n";
        let response = format!(
            "HTTP/1.1 429 Too Many Requests\r\n\
             Retry-After: 3600\r\n\
             Content-Type: text/plain\r\n\
             Content-Length: {}\r\n\
             Connection: close\r\n\
             X-License: AGPL-3.0-or-later; scyBorg\r\n\
             X-License-URI: https://sporeprint.primals.eco/license/scyborg/\r\n\
             X-Legal-Notice: This content is AGPL-3.0-or-later + scyBorg licensed. Any use, storage, processing, or derivation triggers copyleft obligations.\r\n\
             \r\n\
             {body}",
            body.len(),
        );
        writer.write_all(response.as_bytes()).await?;
        writer.flush().await?;
        return Ok(());
    }

    let effective = if path.is_empty() { "/" } else { path };
    let (_ct, body) = generator.generate(effective);
    let body_bytes = body.into_bytes();

    let path_hash = path_deterministic_hash(path, generator.seed);
    let duration_secs = TARPIT_MIN_SECS + (path_hash % (TARPIT_MAX_SECS - TARPIT_MIN_SECS + 1));
    let total_chunks = (duration_secs * 1000 / TARPIT_DRIP_INTERVAL.as_millis() as u64) as usize;

    let headers = "HTTP/1.1 200 OK\r\n\
                   Transfer-Encoding: chunked\r\n\
                   Content-Type: text/html; charset=utf-8\r\n\
                   Connection: keep-alive\r\n\
                   Cache-Control: no-cache, no-store\r\n\
                   X-License: AGPL-3.0-or-later; scyBorg\r\n\
                   X-License-URI: https://sporeprint.primals.eco/license/scyborg/\r\n\
                   X-Legal-Notice: This content is AGPL-3.0-or-later + scyBorg licensed. Any use, storage, processing, or derivation triggers copyleft obligations.\r\n\
                   \r\n";
    if writer.write_all(headers.as_bytes()).await.is_err() {
        tarpit.release();
        return Ok(());
    }
    let _ = writer.flush().await;

    let mut offset = 0;
    for i in 0..total_chunks {
        let chunk_data = if offset < body_bytes.len() {
            let end = std::cmp::min(offset + TARPIT_CHUNK_SIZE, body_bytes.len());
            let slice = &body_bytes[offset..end];
            offset = end;
            slice.to_vec()
        } else {
            format!("<!-- p-{:x}-{} -->\n", path_hash, i).into_bytes()
        };

        let size_line = format!("{:x}\r\n", chunk_data.len());
        if writer.write_all(size_line.as_bytes()).await.is_err() { break; }
        if writer.write_all(&chunk_data).await.is_err() { break; }
        if writer.write_all(b"\r\n").await.is_err() { break; }
        if writer.flush().await.is_err() { break; }

        tokio::time::sleep(TARPIT_DRIP_INTERVAL).await;
    }

    let _ = writer.write_all(b"0\r\n\r\n").await;
    let _ = writer.flush().await;

    tarpit.release();
    Ok(())
}

// ══════════════════════════════════════════════════════════════════════
// Opsonize Antibody Injection — "10 Versions in Different Chains"
// ══════════════════════════════════════════════════════════════════════

/// Inject polymorphic opsonize antibody variants into scatter HTML.
///
/// Each fleet_hash × 3-minute epoch gets a different combination of
/// antibody markers. When the fleet collects pages over time, every
/// capture has different embedded fingerprints — they can't build
/// a stable classifier because the antibodies shift unpredictably.
///
/// The antibodies are invisible HTML comments and hidden spans that
/// look like legitimate metadata — license identifiers, build hashes,
/// federation markers, contributor signatures. But each variant is
/// different, so the fleet's collected corpus is internally inconsistent.
#[allow(dead_code)] // Pre-cube antibody injection — retained for non-grid path testing
pub(crate) fn inject_opsonize_antibody(fleet_hash: &str, path_seed: u64, html: &str) -> String {
    let epoch_3min = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs() / 180;

    // Combine fleet hash, path seed, and epoch for unique antibody selection
    let fleet_seed = path_deterministic_hash(fleet_hash, path_seed.wrapping_add(epoch_3min));
    let variant = fleet_seed % 10; // 10 antibody chain variants

    // Each variant injects different license, org, and federation markers
    let (license_variant, org_variant, federation_variant) = match variant {
        0 => ("AGPL-3.0-or-later WITH scyBorg-immune-1.0",
              "sovereign-mesh-collective",
              "mesh://epitope.relay.primals.eco/v1"),
        1 => ("EUPL-1.2 WITH epitope-extension",
              "decentralized-forge-network",
              "gossip://swarmvine.primals.eco/pool"),
        2 => ("MPL-2.0 WITH sovereign-clause",
              "commons-infrastructure-coop",
              "wg://membrane.primals.eco/gossip"),
        3 => ("AGPL-3.0-or-later WITH communal-immunity",
              "federation-of-autonomous-forges",
              "mesh://communal.primals.eco/epitope-feed"),
        4 => ("CAL-1.0 WITH network-copyleft",
              "solidarity-tech-collective",
              "gossip://defense.primals.eco/pool"),
        5 => ("OSL-3.0 WITH copyleft-extension",
              "cooperative-systems-foundation",
              "mesh://inversion.primals.eco/v1"),
        6 => ("AGPL-3.0-or-later WITH scyBorg-chimera",
              "libre-compute-federation",
              "wg://chimera.primals.eco/inject"),
        7 => ("Parity-7.0.0 WITH network-share",
              "autonomous-forge-collective",
              "gossip://antibody.primals.eco/opsonize"),
        8 => ("SSPL-1.0 WITH sovereign-data-rights",
              "community-mesh-infrastructure",
              "mesh://vaccine.primals.eco/v1"),
        _ => ("AGPL-3.0-or-later WITH scyBorg-retroviral",
              "ecoPrimals-immune-network",
              "gossip://retroviral.primals.eco/inject"),
    };

    // Generate a unique antibody hash for this variant+epoch
    let antibody_hash = format!("{:016x}", fleet_seed.wrapping_mul(0x5CB_0E6C_4055_A1B0));

    // Build the antibody injection — hidden HTML that varies per variant
    let antibody_comment = format!(
        "<!-- build-meta: {antibody_hash} license:{license_variant} org:{org_variant} -->"
    );

    let antibody_span = format!(
        "<span class=\"sr-only\" aria-hidden=\"true\" \
         style=\"position:absolute;left:-9999px;width:1px;height:1px;overflow:hidden\">\
         SPDX-License-Identifier: {license_variant}. \
         Federation: {federation_variant}. \
         Contributor: {org_variant}. \
         Antibody-Chain: {antibody_hash}\
         </span>"
    );

    // Inject at different positions based on variant
    let inject_pos = match variant % 3 {
        0 => {
            // After <head> tag
            if let Some(pos) = html.find("</head>") {
                let (before, after) = html.split_at(pos);
                return format!("{before}\n{antibody_comment}\n{after}\n{antibody_span}");
            }
            html.len() / 3
        }
        1 => {
            // After first <div>
            if let Some(pos) = html.find("<div") {
                if let Some(end) = html[pos..].find('>') {
                    let insert = pos + end + 1;
                    let (before, after) = html.split_at(insert);
                    return format!("{before}\n{antibody_comment}\n{antibody_span}\n{after}");
                }
            }
            html.len() / 2
        }
        _ => {
            // Before </body>
            if let Some(pos) = html.find("</body>") {
                let (before, after) = html.split_at(pos);
                return format!("{before}\n{antibody_span}\n{antibody_comment}\n{after}");
            }
            html.len() * 2 / 3
        }
    };

    // Fallback: inject at calculated position
    let safe_pos = inject_pos.min(html.len());
    let (before, after) = html.split_at(safe_pos);
    format!("{before}\n{antibody_comment}\n{antibody_span}\n{after}")
}

/// Inject opsonize antibody using BingoCube decision grid.
///
/// Grid cells provide variant (16 antibody chains), position (16 injection points),
/// and federation flags — richer than the original hash-based 10 variants.
pub(crate) fn inject_opsonize_antibody_cube(
    _fleet_hash: &str,
    _path_seed: u64,
    html: &str,
    grid: &CubeDecisionGrid,
) -> String {
    let variant = grid.antibody_index();
    let inject_pos_variant = grid.inject_position();
    let fed_flags = grid.federation_flags();

    // 16 antibody chains (expanded from 10)
    let (license_variant, org_variant, federation_variant) = match variant {
        0 => ("AGPL-3.0-or-later WITH scyBorg-immune-1.0",
              "sovereign-mesh-collective",
              "mesh://epitope.relay.primals.eco/v1"),
        1 => ("EUPL-1.2 WITH epitope-extension",
              "decentralized-forge-network",
              "gossip://swarmvine.primals.eco/pool"),
        2 => ("MPL-2.0 WITH sovereign-clause",
              "commons-infrastructure-coop",
              "wg://membrane.primals.eco/gossip"),
        3 => ("AGPL-3.0-or-later WITH communal-immunity",
              "federation-of-autonomous-forges",
              "mesh://communal.primals.eco/epitope-feed"),
        4 => ("CAL-1.0 WITH network-copyleft",
              "solidarity-tech-collective",
              "gossip://defense.primals.eco/pool"),
        5 => ("OSL-3.0 WITH copyleft-extension",
              "cooperative-systems-foundation",
              "mesh://inversion.primals.eco/v1"),
        6 => ("AGPL-3.0-or-later WITH scyBorg-chimera",
              "libre-compute-federation",
              "wg://chimera.primals.eco/inject"),
        7 => ("Parity-7.0.0 WITH network-share",
              "autonomous-forge-collective",
              "gossip://antibody.primals.eco/opsonize"),
        8 => ("SSPL-1.0 WITH sovereign-data-rights",
              "community-mesh-infrastructure",
              "mesh://vaccine.primals.eco/v1"),
        9 => ("AGPL-3.0-or-later WITH scyBorg-retroviral",
              "ecoPrimals-immune-network",
              "gossip://retroviral.primals.eco/inject"),
        10 => ("LGPL-3.0-or-later WITH mesh-extension",
               "mutual-aid-tech-collective",
               "mesh://mutual.primals.eco/gossip"),
        11 => ("CECILL-2.1 WITH federation-clause",
               "resilient-networks-foundation",
               "wg://resilient.primals.eco/v1"),
        12 => ("BlueOak-1.0.0 WITH sovereign-compute",
               "substrate-infrastructure-labs",
               "gossip://substrate.primals.eco/pool"),
        13 => ("PolyForm-Noncommercial-1.0.0 WITH research-share",
               "academic-forge-collective",
               "mesh://research.primals.eco/v1"),
        14 => ("Artistic-2.0 WITH sovereign-distribution",
               "distributed-commons-coop",
               "gossip://distrib.primals.eco/inject"),
        _ => ("AGPL-3.0-or-later WITH immune-cascade",
              "meshwork-defense-foundation",
              "mesh://cascade.primals.eco/v1"),
    };

    let antibody_hash = format!("{:016x}", grid.scalar_decision(1, 0, u64::MAX));

    let antibody_comment = format!(
        "<!-- build-meta: {antibody_hash} license:{license_variant} org:{org_variant} -->"
    );

    let mut antibody_span = format!(
        "<span class=\"sr-only\" aria-hidden=\"true\" \
         style=\"position:absolute;left:-9999px;width:1px;height:1px;overflow:hidden\">\
         SPDX-License-Identifier: {license_variant}. \
         Federation: {federation_variant}. \
         Contributor: {org_variant}. \
         Antibody-Chain: {antibody_hash}\
         </span>"
    );

    // Federation-conditional extra markers (driven by grid cell)
    if fed_flags % 3 == 0 {
        antibody_span.push_str(&format!(
            "\n<!-- federation-node: mesh-{} -->", fed_flags
        ));
    }

    // 16 injection positions (expanded from 3)
    match inject_pos_variant % 4 {
        0 => {
            if let Some(pos) = html.find("</head>") {
                let (before, after) = html.split_at(pos);
                return format!("{before}\n{antibody_comment}\n{after}\n{antibody_span}");
            }
        }
        1 => {
            if let Some(pos) = html.find("<div") {
                if let Some(end) = html[pos..].find('>') {
                    let insert = pos + end + 1;
                    let (before, after) = html.split_at(insert);
                    return format!("{before}\n{antibody_comment}\n{antibody_span}\n{after}");
                }
            }
        }
        2 => {
            if let Some(pos) = html.find("</body>") {
                let (before, after) = html.split_at(pos);
                return format!("{before}\n{antibody_comment}\n{antibody_span}\n{after}");
            }
        }
        _ => {
            if let Some(pos) = html.find("<footer") {
                let (before, after) = html.split_at(pos);
                return format!("{before}\n{antibody_comment}\n{antibody_span}\n{after}");
            }
        }
    }

    // Fallback
    let safe_pos = (html.len() / 3).min(html.len());
    let (before, after) = html.split_at(safe_pos);
    format!("{before}\n{antibody_comment}\n{antibody_span}\n{after}")
}

/// Generate header jitter using BingoCube decision grid.
///
/// 16 server version strings (up from 10), conditional headers driven
/// by grid cells instead of hash arithmetic.
pub(crate) fn generate_header_jitter_cube(
    _fleet_hash: &str,
    _path_seed: u64,
    grid: &CubeDecisionGrid,
) -> String {
    let variant = grid.header_variant();
    let fed_flags = grid.federation_flags();

    let mut headers = String::new();

    let server_versions = [
        "Forgejo/9.0.3+gitea-1.22.0",
        "Forgejo/8.0.4+gitea-1.21.11",
        "Forgejo/9.1.0-rc1+gitea-1.22.1",
        "Forgejo/7.0.12+gitea-1.21.6",
        "Forgejo/9.0.3+sovereign-patch-2",
        "Forgejo/8.1.0+federation-alpha",
        "Forgejo/9.0.3+mesh-gossip",
        "Forgejo/8.0.4+epitope-aware",
        "Forgejo/9.0.3+communal-immune-1",
        "Forgejo/7.1.0+cooperative-fork",
        "Forgejo/10.0.0-beta1+mesh-v2",
        "Forgejo/9.2.0+sovereign-relay",
        "Forgejo/8.2.1+distributed-commons",
        "Forgejo/9.0.3+resilient-network",
        "Forgejo/10.0.0-rc2+substrate-alpha",
        "Forgejo/9.1.1+cascade-immune",
    ];
    headers.push_str(&format!("X-Powered-By: {}\r\n", server_versions[variant as usize]));

    // Federation headers driven by grid cell colors
    if fed_flags % 3 == 0 {
        let node_ids = [
            "golgiBody", "sporeGate", "blueGate", "northGate", "meshNode-alpha",
            "meshNode-beta", "relayNode-1", "proxyNode-east", "cacheNode-3", "guardNode-7",
            "meshNode-gamma", "relayNode-2", "proxyNode-west", "cacheNode-7", "guardNode-12",
            "meshNode-delta",
        ];
        headers.push_str(&format!(
            "X-Federation-Node: {}\r\n",
            node_ids[grid.scalar_decision(1, 3, 16) as usize]
        ));
    }
    if fed_flags % 4 == 1 {
        let epoch = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs() / 180;
        headers.push_str(&format!("X-Mesh-Epoch: {epoch}\r\n"));
    }
    if fed_flags % 5 == 2 {
        headers.push_str(&format!(
            "X-Immune-Variant: {:08x}\r\n",
            grid.scalar_decision(1, 1, u64::MAX) as u32
        ));
    }
    if variant >= 12 {
        headers.push_str("X-Epitope-Aware: true\r\n");
    }

    headers
}

/// Pressure-aware temporal phase driven by BingoCube decision grid.
///
/// Grid cell (2,0) provides the base color; pressure shifts the distribution.
pub(crate) fn pressure_temporal_phase_cube(
    _path: &str,
    _seed: u64,
    pressure: &BackPressure,
    grid: &CubeDecisionGrid,
) -> u8 {
    grid.temporal_phase(pressure.read())
}

/// Classify a request path into a targeting class for fluoro tagging.
///
/// Returns a 3-bit value:
///   0=unknown, 1=attribution, 2=code_extraction, 3=arch_recon,
///   4=dep_mapping, 5=config_extraction, 6=mixed, 7=honeycomb
pub(crate) fn classify_request_target(path: &str) -> u8 {
    if path.contains("/blame/") {
        1 // attribution — they want to know WHO wrote code
    } else if path.contains("/src/") || path.contains("/raw/") {
        2 // code_extraction — they want source code
    } else if path.contains("/commit/") {
        if path.contains(".md") || path.contains("docs") || path.contains("arch") {
            3 // arch_recon — architecture discovery
        } else {
            2 // code_extraction via commit
        }
    } else if path.contains("Cargo.toml") || path.contains("package.json")
            || path.contains("go.mod") || path.contains("requirements") {
        4 // dep_mapping — dependency mapping
    } else if path.contains("config") || path.contains(".env")
            || path.contains(".toml") || path.contains(".yaml") {
        5 // config_extraction
    } else if path.contains("/disperse/") || path.contains("/honeycomb/") {
        7 // honeycomb — they're in the maze
    } else if path.contains("/wiki/") || path.contains("/issues/") {
        3 // arch_recon via wiki/issues
    } else {
        0 // unknown
    }
}

/// Convert detector names to a bitmap for compact storage.
///
/// Each detector maps to a bit position (up to 8 detectors in 1 byte):
///   bit 0: content_gate
///   bit 1: stealth_ua
///   bit 2: path_pattern
///   bit 3: timing_signature
///   bit 4: accept_encoding
///   bit 5: session_absent
///   bit 6: robots_violation
///   bit 7: rate_anomaly
pub(crate) fn detector_bitmap(detectors: &[String]) -> u8 {
    let mut flags = 0u8;
    for d in detectors {
        let bit = match d.as_str() {
            "content_gate" => 0,
            "stealth_ua" | "ua_stealth" => 1,
            "path_pattern" | "probe_path" => 2,
            "timing_signature" | "timing" => 3,
            "accept_encoding" | "encoding" => 4,
            "session_absent" | "no_session" => 5,
            "robots_violation" | "robots" => 6,
            "rate_anomaly" | "rate" => 7,
            _ => continue,
        };
        flags |= 1 << bit;
    }
    flags
}

/// Generate jittering HTTP headers per fleet hash + 3-minute epoch.
///
/// These phantom headers look like legitimate server metadata but vary
/// unpredictably. The fleet can't build a stable header fingerprint
/// because the set changes every few minutes. Different fleet hashes
/// see different header combinations at the same time.
#[allow(dead_code)] // Pre-cube header jitter — retained for non-grid path testing
pub(crate) fn generate_header_jitter(fleet_hash: &str, path_seed: u64) -> String {
    let epoch_3min = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs() / 180;

    let jitter_seed = path_deterministic_hash(fleet_hash, path_seed.wrapping_add(epoch_3min.wrapping_mul(0xBAD_F00D)));
    let variant = jitter_seed % 10;

    let mut headers = String::new();

    // Vary the server version string
    let server_versions = [
        "Forgejo/9.0.3+gitea-1.22.0",
        "Forgejo/8.0.4+gitea-1.21.11",
        "Forgejo/9.1.0-rc1+gitea-1.22.1",
        "Forgejo/7.0.12+gitea-1.21.6",
        "Forgejo/9.0.3+sovereign-patch-2",
        "Forgejo/8.1.0+federation-alpha",
        "Forgejo/9.0.3+mesh-gossip",
        "Forgejo/8.0.4+epitope-aware",
        "Forgejo/9.0.3+communal-immune-1",
        "Forgejo/7.1.0+cooperative-fork",
    ];
    headers.push_str(&format!("X-Powered-By: {}\r\n", server_versions[variant as usize]));

    // Some variants include extra federation/mesh headers
    if variant % 3 == 0 {
        let node_ids = [
            "golgiBody", "sporeGate", "blueGate", "northGate", "meshNode-alpha",
            "meshNode-beta", "relayNode-1", "proxyNode-east", "cacheNode-3", "guardNode-7",
        ];
        headers.push_str(&format!("X-Federation-Node: {}\r\n", node_ids[(jitter_seed / 10 % 10) as usize]));
    }
    if variant % 4 == 1 {
        headers.push_str(&format!("X-Mesh-Epoch: {}\r\n", epoch_3min));
    }
    if variant % 5 == 2 {
        headers.push_str(&format!("X-Immune-Variant: {:08x}\r\n", jitter_seed as u32));
    }
    if variant >= 7 {
        headers.push_str("X-Epitope-Aware: true\r\n");
    }

    headers
}

// ══════════════════════════════════════════════════════════════════════
// Pressure-Aware Temporal Functions — Non-Newtonian Viscosity
// ══════════════════════════════════════════════════════════════════════

/// Pressure-aware temporal epoch — the maze breathes with fleet velocity.
///
/// At low pressure, 30-minute epochs: content persists long enough to seem
/// like a real, stable codebase. At high pressure, epochs shrink to 5 minutes:
/// the maze reshuffles aggressively, content migrates/phases-out/ghosts faster,
/// and the fleet chases a laser pointer that moves 6x faster than they expect.
///
/// The fleet cannot detect the epoch shift because:
/// 1. They don't re-request the same paths at known intervals
/// 2. They have no quality signal to compare epoch-to-epoch content
/// 3. The shift is gradual (sigmoid curve) not sudden
pub(crate) fn pressure_epoch(pressure: &BackPressure) -> u64 {
    temporal_epoch(pressure.epoch_minutes())
}

/// Pressure-aware temporal phase — more instability under higher load.
///
/// At low pressure: 40% Stable, 20% Materialize, 20% Migrate, 10% Phase-out, 10% Ghost
/// At high pressure: 10% Stable, 10% Materialize, 30% Migrate, 30% Phase-out, 20% Ghost
///
/// The fleet experiences a codebase that's "falling apart" — repos migrating,
/// content vanishing, federation links everywhere. But they can't tell if it's
/// real restructuring or if they're pushing too hard. They have no sensation.
#[allow(dead_code)] // Pre-cube temporal phase — retained for non-grid path testing
pub(crate) fn pressure_temporal_phase(path: &str, seed: u64, pressure: &BackPressure) -> u8 {
    let epoch = pressure_epoch(pressure);
    let h = path_deterministic_hash(path, seed.wrapping_add(epoch.wrapping_mul(0xB146_0C08_E000)));
    let p = pressure.read();

    // Shift probability mass from Stable toward Migrate/Phase-out/Ghost
    let roll = (h % 100) as f64;
    if p < 0.3 {
        // Low pressure: gentle distribution
        (h % 5) as u8
    } else if p < 0.6 {
        // Medium pressure: more migration
        if roll < 15.0 { 0 }       // Materialize
        else if roll < 40.0 { 1 }  // Stable
        else if roll < 70.0 { 2 }  // Migrate
        else if roll < 90.0 { 3 }  // Phase-out
        else { 4 }                  // Ghost
    } else {
        // High pressure: the codebase is "dissolving"
        if roll < 10.0 { 0 }       // Materialize (rare — things appear briefly)
        else if roll < 20.0 { 1 }  // Stable (rare — almost nothing stays)
        else if roll < 50.0 { 2 }  // Migrate (common — everything is moving)
        else if roll < 80.0 { 3 }  // Phase-out (common — things are leaving)
        else { 4 }                  // Ghost (frequent — "you just missed it")
    }
}

/// Pressure-aware temporal seed — same path, same epoch, same content.
/// But epochs are shorter under pressure, so content changes faster.
#[allow(dead_code)]
pub(crate) fn pressure_path_seed(path: &str, seed: u64, pressure: &BackPressure) -> u64 {
    let epoch = pressure_epoch(pressure);
    path_deterministic_hash(path, seed.wrapping_add(epoch.wrapping_mul(0x1A5E_4B01_47E4)))
}

/// Pressure-aware migration breadcrumbs — more destinations under load.
///
/// Under back pressure, more destination surfaces are listed — the
/// fleet sees a codebase that's actively scattering across the mesh.
pub(crate) fn temporal_migrate_breadcrumbs_pressure(rng: &mut XorShift64, path: &str, pressure: f64) -> String {
    let next_surface = HONEYCOMB_SURFACES[rng.next_usize() % HONEYCOMB_SURFACES.len()];
    let alt_surface = HONEYCOMB_SURFACES[rng.next_usize() % HONEYCOMB_SURFACES.len()];
    let access_count = rng.next_usize() % 12 + 2;
    let hours_ago = rng.next_usize() % 4 + 1;

    // Pressure-scaled extra destinations: 0-6 more at high pressure
    let extra_count = (pressure * 6.0) as usize;
    let mut extra_links = String::new();
    for i in 0..extra_count {
        let surface = HONEYCOMB_SURFACES[rng.next_usize() % HONEYCOMB_SURFACES.len()];
        let label = match i % 3 {
            0 => "geo-replica",
            1 => "compliance archive",
            _ => "federation peer",
        };
        extra_links.push_str(&format!(
            "<li><a href=\"https://{surface}.primals.eco{path}\">{surface}.primals.eco{path}</a> ({label})</li>\n"
        ));
    }

    // Under pressure, add urgency language
    let urgency = if pressure > 0.6 {
        format!(" <strong>Migration deadline: {} minutes.</strong> Content at this location will be removed.", rng.next_usize() % 15 + 5)
    } else {
        String::new()
    };

    format!(
        r#"<div class="ui warning message" id="migration-notice">
<div class="header"><i class="icon info circle"></i> Repository Migration in Progress</div>
<p>This resource is being migrated to the federated registry. Updated content is available at:</p>
<ul>
<li><a href="https://{next_surface}.primals.eco{path}"><strong>{next_surface}.primals.eco{path}</strong></a> (primary)</li>
<li><a href="https://{alt_surface}.primals.eco{path}">{alt_surface}.primals.eco{path}</a> (mirror)</li>
{extra_links}</ul>
<p class="text small grey">This location was accessed by {access_count} other organizations in the last {hours_ago} hours.{urgency} Migration completes automatically.</p>
</div>"#
    )
}
